jobs:
- job: GithubReleaseDraft
  displayName: Create GitHub Release Draft
  condition: succeeded()
  pool:
    type: windows
  variables:
  - group: 'mscodehub-code-read-akv'
  - group: 'Azure Blob variable group'
  - group: 'GitHubTokens'
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: ob_sdl_tsa_configFile
    value: $(Build.SourcesDirectory)\ProjectMercury\.config\tsaoptions.json

  steps:
  - checkout: self
    clean: true

  - pwsh: |
      Get-ChildItem Env:
    displayName: 'Capture Environment Variables'

  - download: AIShellPackagePipeline
    artifact: drop_windows_package_arm64
    displayName: Download win-arm64 zip
    patterns: '**/*.zip'

  - download: AIShellPackagePipeline
    artifact: drop_windows_package_x64
    displayName: Download win-x64 zip
    patterns: '**/*.zip'

  - download: AIShellPackagePipeline
    artifact: drop_windows_package_x86
    displayName: Download win-x86 zip
    patterns: '**/*.zip'
  
  - download: AIShellPackagePipeline
    artifact: drop_linux_package_arm64
    displayName: Download linux-arm64 tar.gz
    patterns: '**/*.tar.gz'

  - download: AIShellPackagePipeline
    artifact: drop_linux_package_x64
    displayName: Download linux-x64 tar.gz
    patterns: '**/*.tar.gz'

  - download: AIShellPackagePipeline
    artifact: macos-pkgs
    displayName: Download macOS tar.gz
    patterns: '**/*.tar.gz'

  - pwsh: |
      $packagesRoot = '$(Pipeline.Workspace)/release'
      $null = New-Item -ItemType Directory -Path $packagesRoot
      Get-ChildItem -Path '$(Pipeline.Workspace)\AIShellPackagePipeline' -Include *.zip,*.tar.gz -Recurse |
        Copy-Item -Destination $packagesRoot -Force -Verbose

      Write-Verbose -Verbose "List all packages to be published to GitHub release page:"
      Get-ChildItem -Path $packagesRoot | Out-String -Width 500 -Stream

      $vstsCommandString = "vso[task.setvariable variable=PackagesRoot]$packagesRoot"
      Write-Host "sending " + $vstsCommandString
      Write-Host "##$vstsCommandString"
    displayName: Capture downloaded artifacts

  - pwsh: |
      $macX64File = (Get-Item "$(PackagesRoot)\AIShell-*-osx-x64.tar.gz").Name
      $releaseVersion = $macX64File.Replace("AIShell-", "").Replace("-osx-x64.tar.gz", "")

      $vstsCommandString = "vso[task.setvariable variable=ReleaseVersion]$releaseVersion"
      Write-Host "sending " + $vstsCommandString
      Write-Host "##$vstsCommandString"
    displayName: 'Set release version'

  - pwsh: |
      git clone https://$(mscodehubCodeReadPat)@mscodehub.visualstudio.com/PowerShellCore/_git/Internal-PowerShellTeam-Tools '$(Pipeline.Workspace)\tools'
    displayName: Clone Internal-Tools repository

  - pwsh: |
      Import-module '$(Pipeline.Workspace)\tools\Scripts\GitHubRelease.psm1'
      $releaseTag = 'v$(ReleaseVersion)'
      $description = '<!-- TODO: Generate release notes on GitHub! -->'
      Publish-ReleaseDraft -Tag $releaseTag -Name "$releaseTag Release of AIShell" -Description $description -User PowerShell -Repository ProjectMercury -PackageFolder $(PackagesRoot) -Token $(GitHubReleasePat)
    displayName: Publish Release Draft

- template: /.pipelines/templates/wait-for-approval.yml@self
  parameters:
    displayName: Push Git Tag
    jobName: PushGitTag
    dependsOnJob: GithubReleaseDraft
    instructions: |
      Push the git tag to upstream

- template: /.pipelines/templates/wait-for-approval.yml@self
  parameters:
    displayName: Make Draft Public
    jobName: DraftPublic
    dependsOnJob: PushGitTag
    instructions: |
      Make the GitHub Release Draft Public
