parameters:
  - name: publish
    default: false
    type: boolean

jobs:
- job: NuGetPublish
  displayName: Publish to NuGet
  condition: succeeded()
  pool:
    type: release
    os: windows
  templateContext:
    inputs:
      - input: pipelineArtifact
        pipeline: AIShellPackagePipeline
        artifactName: drop_nupkg_package
  variables:
  - group: 'mscodehub-code-read-akv'
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'

  steps:
   - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem '$(Pipeline.Workspace)/drop_nupkg_package/*.nupkg' -recurse
    displayName: List nupkg package

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    condition: and(ne('${{ parameters.publish }}', 'false'), succeeded())
    inputs:
      command: push
      packagesToPush: '$(Pipeline.Workspace)/drop_nupkg_package/*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: PowerShellNuGetOrgPush
