parameters:
  Architecture: 'x64'

jobs:
- job: build_${{ parameters.Architecture }}
  displayName: Build Windows ${{ parameters.Architecture }}
  condition: succeeded()
  pool:
    type: windows
  variables:
  - name: runCodesignValidationInjection
    value: false
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - group: DotNetPrivateBuildAccess
  - group: certificate_logical_to_actual
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: repoRoot
    value: $(Build.SourcesDirectory)\ProjectMercury
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: ob_sdl_binskim_enabled
    value: true
  - name: ob_sdl_tsa_configFile
    value: $(repoRoot)\.config\tsaoptions.json
  - name: Architecture
    value: ${{ parameters.Architecture }}
  - name: Runtime
    value: 'win-$(Architecture)'
  - name: ob_sdl_sbom_packageName
    value: 'AIShell.Windows.${{ parameters.Architecture }}'
  #CodeQL tasks added manually to workaround signing failures
  - name: ob_sdl_codeql_compiled_enabled
    value: false

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true

  - template: /.pipelines/templates/update-nuget-config.yml@self
    parameters:
      repoRoot: $(repoRoot)

  # Add CodeQL Init task right before your 'Build' step.
  - task: CodeQL3000Init@0
    env:
      ob_restore_phase: true
    inputs:
      Enabled: true
      Language: csharp

  - pwsh: |
      Import-Module $(repoRoot)/build.psm1 -Force
      Install-Dotnet

      $runtime = '$(Runtime)'
      Write-Verbose -Message "Building with Runtime: $runtime"
      $result = Start-Build -Runtime $runtime -Configuration Release -Clean -PassThru -Verbose

      if ($result) {
        $vstsCommandString = "vso[task.setvariable variable=AppDir]$result.App"
        Write-Host ("sending " + $vstsCommandString)
        Write-Host "##$vstsCommandString"

        $vstsCommandString = "vso[task.setvariable variable=ModuleDir]$result.Module"
        Write-Host ("sending " + $vstsCommandString)
        Write-Host "##$vstsCommandString"
      }
    displayName: 'Build Windows-$(Architecture)'
    env:
      ob_restore_phase: true

  # Add CodeQL Finalize task right after your 'Build' step.
  - task: CodeQL3000Finalize@0
    env:
      ob_restore_phase: true

  - pwsh: |
      Get-ChildItem $(AppDir) | Out-String -width 500 -Stream
      Get-ChildItem $(ModuleDir) | Out-String -width 500 -Stream
    displayName: 'List build artifacts'
    env:
      ob_restore_phase: true

  - template: /.pipelines/templates/sign-files.yml@self
    parameters:
      appPath: '$(AppDir)'
      modulePath: '$(ModuleDir)'
      repoRoot: '$(repoRoot)'

  - template: /.pipelines/templates/step/finalize.yml@self
